### ISSUE TITLE
doesn't seem to work for latest/env presets

### ISSUE THREAD

**Issue by graingert** [jamonkko/babel-plugin-rename-umd-globals#38]
My babelrc looks like this:
```json
{
  "presets": [
    ["env", {
      "modules": "umd",
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }]
  ],
  "plugins": [
    ["rename-umd-globals", {
      "jquery": ["jQuery", "$"]
    }]
  ]
}
```

but rename-umd-globals doesn't do anything.

**Comment by jamonkko** [comment]
Order matters.

I tried out that myself and it indeed seems not to rename with that configuration. I suspect that it might be because this happens:
1. plugins are applied to code, and at this point there are no umd globals yet generated for the plugin to rename
2. presets env modules are applied and the umd specific code is generated. And that code is not anymore passed to the explicit plugins to modify.

You could try to not use the modules: umd thing but try instead:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }]
  ],
  "plugins": [
    "transform-es2015-modules-umd",
    ["rename-umd-globals", {
      "jquery": ["jQuery", "$"]
    }]
  ]
}
```

I'm not sure if that fits your use case (you need to check the output) but at least with that configuration the umd formatted code is passed to the rename plugin. 

Also using `transform-es2015-modules-umd` plugin explicitly seemed to produce identical code as using that presets env modules umd option so it might be ok.

**Comment by graingert** [comment]
I went for this in the end https://github.com/Bttstrp/bootstrap-switch/commit/1fec545ca5901bdb6c7c4b79085cdd4121473d22#diff-c32e0165919a8ea52bc37b044f229a55R3

**Comment by jamonkko** [comment]
Good that you found a solution! 

I wrote this plugin to rename the globals that are added to global scope from the umd module itself (in the scenario where the script is just included to page). I never considered to add aliases for any dependencies that are already in global scope. 

Btw, I have actually used same solution as you ended up doing to get dependencies from window :)
